# CI for LaMEM
# inspired by CI actions used in GEOS
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux: 
  strategy:
      matrix:
      ci:
        - cxx_compiler: g++-10
          c_compiler: gcc-10
          build_type: Release
          cxxstd: 14
          arch: 64
          packages: 'g++-10-multilib gcc-10-multilib'
          cmake: 3.13.*
          os: ubuntu-20.04
                  
  runs-on: ${{ matrix.ci.os }}
  steps:

    - name: 'Install'
      run: |
        set -e
        uname -a
        sudo -E apt-get update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install make julia ${{ matrix.ci.packages }}
        # Now create workspace directories, to later copy the pre-compiled PETSC libraries there
        sudo -E mkdir /workspace
        
    - name: 'Check Out'
      uses: actions/checkout@v3
