# CI for LaMEM
# inspired by CI actions used in GEOS
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    name: 'Linux'
    strategy:
      matrix:
        ci:
        - cxx_compiler: g++-12
          c_compiler: gcc-12
          build_type: Release
          cxxstd: 20
          arch: 64
          packages: 'g++-12-multilib gcc-12-multilib'
          cmake: 3.22.*
          os: ubuntu-22.04
        
    runs-on: ${{ matrix.ci.os }}
    steps:

    - name: 'Install compilers'
      run: |
        set -e
        uname -a
        sudo -E apt-get update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install make ${{ matrix.ci.packages }}
        # Now create workspace directories, to later copy the pre-compiled PETSC libraries there
        sudo -E mkdir /workspace
        sudo -E mkdir /workspace/destdir

    - name: 'Install julia'
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: 'Checkout LaMEM'
      uses: actions/checkout@v3

    - name: 'Install/compile PETSc & LaMEM'
      run: |
        cd test
        julia --project=. setup_packages.jl
        cd ..
        
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-runtest@latest
  
